ktor:
    deployment:
        port: 8080
        host: "0.0.0.0"
    application:
        modules:
            - com.example.ApplicationKt.module
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"